<a href="https://colab.research.google.com/github/rahwinside/fastai/blob/main/lesson_0/1_numpy_essentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMPORTANT**: Please avoid creating unnecessary arrays: use the arrays declared in section 1; create additional arrays only if necessary!

# **NumPy Essentials**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. This library is widely used for numerical analysis, matrix computations, and mathematical operations.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

---



# 1. Creating an array

Create an 1D, 2D and a 3D array.

In [4]:
import numpy as np
# TODO: create 1D array
arr1=np.array([10, 20, 30, 40, 50])

# TODO: create 2D array
arr2=np.array([[0, 2, 4],[1, 3, 5]])

# TODO: create 3D array
arr3=np.array([0,1,2], ndmin=3)

# 2. Basic array operations

- Add, subtract, multiply and divide two arrays
- Initialize an array of zeroes
- Initialize an array of ones
- Printing an array



In [6]:
arr2=np.array([5, 15, 4, 25, 10])
# TODO: print an array
print("First Array: {}".format(arr1))
print("Second Array: {}".format(arr2))

# TODO: add arrays
print("Added Array: {}".format(np.add(arr1, arr2)))

# TODO: subtract arrays
print("Subtracted Array: {}".format(np.subtract(arr1, arr2)))

# TODO: multiply arrays
print("Multiplied Array: {}".format(np.multiply(arr1, arr2)))

# TODO: divide arrays
print("Divided Array: {}".format(np.divide(arr1, arr2)))    

First Array: [10 20 30 40 50]
Second Array: [ 5 15  4 25 10]
Added Array: [15 35 34 65 60]
Subtracted Array: [ 5  5 26 15 40]
Multiplied Array: [  50  300  120 1000  500]
Divided Array: [2.         1.33333333 7.5        1.6        5.        ]


# 3. Arrays, into it!
- Indexing and slicing an array
- Print n th row of a 2D array
- Print n th column of a 2D array
- Reshape an array
- Stacking multiple arrays
- Deep copy and Shallow copy

In [7]:
# TODO: indexing and slicing an array
print("Array Index no 2 : {}".format(arr1[1]))
print("Slice of Array (last 3 elements): {}".format(arr1[-3:]))
print("Slice of Array (elements 1 to 4): {}".format(arr1[0:4]))

# TODO: Print n th row of a 2D array
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2nd row: {}".format(arr3[1,:]))

# TODO: Print n th column of a 2D array
print("1st column: {}".format(arr3[:,0]))

# TODO: Stacking multiple arrays
print("Stacked Arrays: {}".format(np.stack((arr1,arr2),0)))

# TODO: Reshape an array
print("2D Array flattened as 1D: {}".format(arr3.flatten()))
print("1D Array reshaped as 5x2: \n{}".format(np.stack((arr1,arr2),0).reshape(5,2)))

# TODO: Deep copy and Shallow copy
a=np.array([1,2,3])
b=a.view()
a[0]=10
a=a.reshape(1,3)
print("For Shallow copy shape changes to a do not occur in b but memory changes are common")
print(a)
print(b)
print("For Deep Copy memory changes in a do not occur in b")
a=a.flatten()
b=a.copy()
a[0]=999
print(a)
print(b)


Array Index no 2 : 20
Slice of Array (last 3 elements): [30 40 50]
Slice of Array (elements 1 to 4): [10 20 30 40]
2nd row: [4 5 6]
1st column: [1 4 7]
Stacked Arrays: [[10 20 30 40 50]
 [ 5 15  4 25 10]]
2D Array flattened as 1D: [1 2 3 4 5 6 7 8 9]
1D Array reshaped as 5x2: 
[[10 20]
 [30 40]
 [50  5]
 [15  4]
 [25 10]]
For Shallow copy shape changes to a do not occur in b but memory changes are common
[[10  2  3]]
[10  2  3]
For Deep Copy memory changes in a do not occur in b
[999   2   3]
[10  2  3]


# 4. NumPy methods
NumPy has useful methods that simplify and allow greater degree of manipulation of arrays.
This section is completely open, unstructured!
Please go ahead and add all the interesting methods you've discovered! (Mention appropriate description as comments for the same)

In [28]:
#To copy and array to another
arr4=np.array([8,12,32,4,1])
np.copyto(arr4,arr1)
print("Copied array:",arr4)

#Return the shape of an array
np.shape([[1,2,3]])

#Gives a new shape to an array without changing its data
a = np.arange(10).reshape((2,5))
print(a)

#To get transpose of an array
arr = [[2,4,5],[3,6,7]]
print("Transposed array:",np.transpose(arr))

#To remove axes of length one 
arr4=np.array([[1,2]])
print("Squezed array:",np.squeeze(arr4))

#To split an array into sub array
xarr=np.array([3,4,5,9,0,7])
print("Sub arrays': ",np.split(xarr, 3))

#To repeat elements of an array
print("Modified array: ",np.repeat(xarr,3))

#To repeat an array
print(np.tile(arr1,2))

#To find unique elements of array
uarr = np.array([1,2,4,3,3,2,1,])
print("Unique elements of array: ",np.unique(uarr))

#To insert elements in an array
print("Array after insertion: ",np.insert(xarr,3,1))

#To add elements to the end of the array
print("Array after insertion at the end: ",np.append(xarr,[2,3]))

#To roll array elements
barr = np.arange(5)
print(np.roll(barr, 3))

#To delete elements of an array
print("Array after deletion: ",np.delete(arr,1,1))

#To reverse
print("Reveresed array: ",np.flip(xarr))

#To assemble an nd-array from nested lists of blocks
y = np.array([11,12,13])
z = np.array([15,16,18])
print(np.block([y,z, 20]))

#To return a contiguous flattened array
x = np.array([[11,14,15], [20,22,25]])
print(np.ravel(x))

Copied array: [10 20 30 40 50]
[[0 1 2 3 4]
 [5 6 7 8 9]]
Transposed array: [[2 3]
 [4 6]
 [5 7]]
Squezed array: [1 2]
Sub arrays':  [array([3, 4]), array([5, 9]), array([0, 7])]
Modified array:  [3 3 3 4 4 4 5 5 5 9 9 9 0 0 0 7 7 7]
[10 20 30 40 50 10 20 30 40 50]
Unique elements of array:  [1 2 3 4]
Array after insertion:  [3 4 5 1 9 0 7]
Array after insertion at the end:  [3 4 5 9 0 7 2 3]
[2 3 4 0 1]
Array after deletion:  [[2 5]
 [3 7]]
Reveresed array:  [7 0 9 5 4 3]
[11 12 13 15 16 18 20]
[11 14 15 20 22 25]


# 5. Properties of an array
Just like functions and methods, a NumPy array has properties!
This section is completely open, unstructured!
Please go ahead and add all the interesting methods you've discovered! (Mention appropriate description as comments for the same)

In [ ]:
# write them all!

# 6. Matrix operations
- Inner product
- Dot product
- Transpose
- Trace
- Rank
- Determinant
- True inverse
- Pseudo inverse
- Flatten
- Eigenvalues and eigenvectors

*Note: understand the @ operator and its significance!*

In [ ]:
# TODO: Inner product


# TODO: Dot product


# TODO: Transpose


# TODO: Trace


# TODO: Rank


# TODO: Determinant


# TODO: True inverse


# TODO: Pseudo inverse


# TODO: Flatten


# TODO: Eigenvalues and eigenvectors



# 7. 10 useful NumPy methods you should know!
**show histograms wherever necessary**
- linspace
- arange
- digitize
- repeat
- histogram
- random (what is seed, randint and different random distributions: binomial, normal, exponential, gaussian, etc., and plot their histograms)
- polyfit
- squeeze
- argmax
- loadtxt and savetxt




In [ ]:
# TODO: linspace

In [ ]:
# TODO: arange

In [ ]:
# TODO: digitize

In [ ]:
# TODO: repeat

In [ ]:
# TODO: histogram

In [ ]:
# TODO: random

In [ ]:
# TODO: polyfit

In [ ]:
# TODO: squeeze

In [ ]:
# TODO: argmax

In [ ]:
# TODO: loadtxt and savetxt



---


# **Congratulations!**
## Now you know how to perform basic linear algebra operations with NumPy to get you started with deep learning!

### Proceed to chapter 2 to learn about DataFrames and how to handle them with pandas!